kind: Service
apiVersion: v1
metadata:
  name: sosmed-service
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: sosmed
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sosmed-deployment
spec:
  selector:
    matchLabels:
      app: sosmed
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: sosmed
        image: farman17/sosmediart-pesbuk
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sosmed-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sosmed.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: sosmed-service
          servicePort: 80
